name: PlotSquaredExpansion
version: '1.0-SNAPSHOT'
main: com.f1shy312.plotsquaredexpansion.PlotSquaredExpansion
api-version: '1.20'
authors: [ Das_F1sHy312 ]
description: Modular Feature Expansion for PlotSquared v7-Premium
website: f1shy312.com
softdepend: [ PlotSquared ]

permissions:
  plotsquaredexpansion.settings:
    description: "Access to plot settings GUI"
    default: true
  plotsquaredexpansion.admin:
    description: "Administrative permissions"
    default: op
